### ISSUE TITLE
my fail

### ISSUE THREAD

**Issue by Domosed-gamin** [deqyra/PicrossEngine#1] opened 2020-05-16 14:01 UTC
Hi. Interesting project. I try to build and failed. Sorry, I'm full nab. Please help me to compile your project.
```

ringo@qwerty:~/Загрузки$ cd PicrossEngine-master/
ringo@qwerty:~/Загрузки/PicrossEngine-master$ ls
CHANGELOG.md              cmake_defines.hpp  core  lib         list.todo  picross_cli    README.md  solving  tools
cmake_defines.config.hpp  CMakeLists.txt     io    LICENSE.md  main.cpp   picross_shell  resources  tests
ringo@qwerty:~/Загрузки/PicrossEngine-master$ mkdir build && cd build
ringo@qwerty:~/Загрузки/PicrossEngine-master/build$ cmake ..
CMake Error: Could not find cmake module file: CMakeDetermineDESCRIPTIONCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_DESCRIPTION_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_DESCRIPTION_COMPILER
CMake Error: Could not find cmake module file: /home/ringo/Загрузки/PicrossEngine-master/CMakeFiles/3.7.2/CMakeDESCRIPTIONCompiler.cmake
CMake Error: Could not find cmake module file: CMakeDetermineA Picross grid solverCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_A Picross grid solver_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_A Picross grid solver_COMPILER
CMake Error: Could not find cmake module file: /home/ringo/Загрузки/PicrossEngine-master/CMakeFiles/3.7.2/CMakeA Picross grid solverCompiler.cmake
CMake Error at CMakeLists.txt:67 (project):
  No CMAKE_DESCRIPTION_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_DESCRIPTION_COMPILER to the full path to the compiler, or to the
  compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeDESCRIPTIONInformation.cmake
CMake Error at CMakeLists.txt:67 (project):
  No CMAKE_A Picross grid solver_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_A Picross grid solver_COMPILER to the full path to the compiler, or
  to the compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeA Picross grid solverInformation.cmake
CMake Error: CMAKE_DESCRIPTION_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_A Picross grid solver_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/ringo/Загрузки/PicrossEngine-master/CMakeFiles/CMakeOutput.log".

```
Debian, cmake version 3.7.2, gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by deqyra** [comment] 2020-06-11 16:49
Hi, thanks for taking the time to open an issue and sorry for the late reply. I didn't try building the project on a real Linux environment, which I'm about to get into right now. I'll keep this updated.

**Comment by deqyra** [comment] 2020-06-11 21:12
@Domosed-gamin The errors are caused by the `DESCRIPTION` parameter in the `project` call of [CMakeLists.txt#68](https://github.com/deqyra/PicrossEngine/blob/release-v1.1/CMakeLists.txt#L68), which is unsupported by CMake versions below 3.8.  
While it _is_ possible to make it work for versions below 3.8, it also happens that C++17 features are only supported by CMake 3.8 and above. As a result, I bumped the minimum required CMake version to 3.8 in [commit 4d1ac3d](https://github.com/deqyra/PicrossEngine/commit/4d1ac3d041fc79bb0399953c1dbbfa332d6cd2e4).

You'll need to update CMake before trying again (and make sure to pull `master` again, as I fixed a header which wouldn't compile). I'll close the issue for now, feel free to reopen it your problem isn't solved.

**Closed as completed by deqyra** 2020-06-11 21:12 UTC
